(use socket)
(define (message msg)
(define unix-socket (socket af/unix sock/stream))
  (socket-connect unix-socket (unix-address "TestePP2"))
  (socket-send unix-socket msg)
  (socket-close unix-socket)
  )
