(use socket)
(define username "rpissardo: ")
(define (message msg)
(define unix-socket (socket af/unix sock/stream))
  (socket-connect unix-socket (unix-address "TestePP2"))
  (socket-send unix-socket (string-append username msg))
  (socket-close unix-socket)
  )
