(use socket)
(define (server-on)
(define unix-socket (socket af/unix sock/stream))
(define backlog 1)
(define socket-pathname "TestePP2") 
(socket-bind unix-socket (unix-address socket-pathname))
(socket-listen unix-socket backlog)
(let* ((connected-socket (socket-accept unix-socket))
         (message-length 256)
         (received-data (socket-receive connected-socket message-length)))
      (printf "'~A'~%" received-data)
      (socket-close connected-socket)
      (socket-close unix-socket)
      (delete-file socket-pathname)
      (server-on)
    ))
(server-on)
